---

title: SignalNoise
description: SignalNoise website

url: https://signalnoiseongithub.github.io/www
baseurl: /www

permalink: pretty

markdown: kramdown
kramdown:
  input: GFM

highlighter: rouge

defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post

collections:
  smartphone:
    output: true
    permalink: /:collection/:name

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-feed

author: signalnoise

#google_analytics: 
